### ISSUE TITLE
Include account comments in Explorer opening page

### ISSUE THREAD

**Issue by catenocrypt** [mikroncoin/mikron_restapi_py#7]
Include account comments in Explorer opening page, in the list of recent transactions, and in the list of top accounts.
Part of Account Comment, Issue #6 .
Depends on node features, RPC calls ledger and blocks_info should include comments, see https://github.com/mikroncoin/mikron_node/issues/85 and 86.

**Comment by optout21** [comment]
Done (master branch), dependency: node v 2.0.1
